
## Executive Summary {-}

The purpose of the Thompson-Shuswap Watershed Connectivity Restoration Plan (WCRP) is to restore and protect the salmon populations of the Thompson-Shuswap region through collaborative, holistic, and culturally grounded approaches that honor the Secwépemc people's traditional knowledge and rights. This plan is led by the Secwepemc Fisheries Commission (SFC) with logistical support from the Canadian Wildlife Federation (CWF) and aims to improve understanding of habitat connectivity for Chinook Salmon (*Onchorhynchus tschawystcha*), Coho Salmon (*O. kisutch*), Sockeye Salmon (*O. nerka*) and steelhead (*O. mykiss*), herein referred to as Pacific salmon and steelhead, in the Bonaparte River, Bessette Creek, and Eagle River watersheds and inform efforts to close knowledge gaps and plan and prioritize restoration. Local data and knowledge are combined with connectivity modelling to estimate current connectivity status and identify structures that potentially block the most habitat. This informs the prioritization of field assessments to close the most significant knowledge gaps efficiently. Information from field assessments of barrier status and habitat condition are incorporated into the model, improving understanding of which barriers block the most habitat, and informing restoration prioritization. As knowledge gaps are closed and barriers are addressed, this plan will be revised to summarize progress and provide updated estimates of connectivity status and the status and relative importance of remaining structures. 

In the Bonaparte River watershed, 205.05 km of Pacific salmon and steelhead habitat are currently connected to the ocean and 51.37 km are disconnected from it. This means that 80.0% of the 256.42 km of total habitat is connected. In this watershed,  37 structures potentially disconnect Pacific salmon and steelhead habitat. Of these, 3 are identified as barriers in need of rehabilitation (priority barriers), 0 are identified as barriers that do not warrant rehabilitation (non-actionable), and 34 require further field assessment. 

In the Bessette Creek watershed, 65.29 km of Pacific salmon and steelhead habitat are currently connected to the ocean and 20.80 km are disconnected from it. This means that 75.8% of the 86.09 km of total habitat is connected. In this watershed,  9 structures potentially disconnect Pacific salmon and steelhead habitat. Of these, 0 are identified as barriers in need of rehabilitation (priority barriers), 0 are identified as barriers that do not warrant rehabilitation (non-actionable), and 9 require further field assessment.  

In the Eagle River watershed, 154.22 km of Pacific salmon and steelhead habitat are currently connected to the ocean and 9.37 km are disconnected from it. This means that 94.3% of the 163.59 km of total habitat is connected. In this watershed,  13 structures potentially disconnect Pacific salmon and steelhead habitat. Of these, 2 are identified as barriers in need of rehabilitation (priority barriers), 0 are identified as barriers that do not warrant rehabilitation (non-actionable), and 11 require further field assessment. 

![Figure 1: Map of Pacific salmon and steelhead habitat and structures that are confirmed or potential barriers to fish passage in the Bonaparte River watershed as of May 2026. Structure data were obtained from BCFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that one or more Pacific salmon and steelhead could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by one or more Pacific salmon and steelhead for spawning or rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures).](content/images/Fig_1_Bonp.png){#Fig_1_Bonp}

![Figure 2: Map of Pacific salmon and steelhead habitat and structures that are confirmed or potential barriers to fish passage in the Bessette Creek watershed as of May 2026. Structure data were obtained from BCFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that one or more Pacific salmon and steelhead could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by one or more Pacific salmon and steelhead for spawning or rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures).](content/images/Fig_2_Bessette.png){#Fig_2_Bessette}

![Figure 3: Map of Pacific salmon and steelhead habitat and structures that are confirmed or potential barriers to fish passage in the Eagle River watershed as of May 2026. Structure data were obtained from BCFishPass and the Canadian Aquatic Barriers Database(aquaticbarriers.ca). The accessibility model represents areas of the watershed that one or more Pacific salmon and steelhead could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by one or more Pacific salmon and steelhead for spawning or rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick red lines represent habitat considered to be fully disconnected.](content/images/Fig_3_Eagle.png){#Fig_3_Eagle}

![Figure 4: Habitat Accumulation Curve (HAC) showing structures in the Bonaparte River watershed as of May 2026. Structures are ranked based on how much (km) habitat for Pacific salmon and steelhead is upstream. The y-axis represents the cumulative amount of potential spawning and rearing habitat gain (km). Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan.](content/images/bonp-hac.png){#bonp-hac}

![Figure 5: Habitat Accumulation Curve (HAC) showing structures in the Bessette Creek watershed as of May 2026. Structures are ranked based on how much (km) habitat for Pacific salmon and steelhead is upstream. The y-axis represents the cumulative amount of potential spawning and rearing habitat gain (km). Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan.](content/images/bessette-hac.png){#bassette-hac}

![Figure 6: Habitat Accumulation Curve (HAC) showing structures in the Eagle River watershed as of May 2026. Structures are ranked based on how much (km) habitat for Pacific salmon and steelhead is upstream. The y-axis represents the cumulative amount of potential spawning and rearing habitat gain (km). Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan.](content/images/eagle-hac.png){#eagle-hac}

This WCRP was initiated in 2023. Since then, the passability of 71 structures has been assessed, and further habitat assessments were completed at 0 of these. Five priority barriers have been identified among the three watersheds. 
