
# Acknowledgements and References {-}

## Recommended Citation 

Roberts, D., L. Amiro, R. Macleod, W. Richards, N. Mazany-Wright, F. Montgomery, B. Rebellato, and N. W. R. Lapointe. 2026. Stewiacke watershed connectivity restoration plan. Confederacy of Mainland Mi’kmaq. Nova Scotia, Canada. 


## Acknowledgements {-}

CMM and CWF recognize that the lands and waters that form the basis of this plan are the traditional unceded territory of the Mi’kmaw peoples. Plan development was funded by the Department of Fisheries and Ocean’s Habitat Stewardship Program for Species at Risk. Members of the planning team (Appendix B) are passionate about the conservation and restoration of freshwater ecosystems and the species they support, and contributed feedback, guidance, and knowledge. Accessibility models were inspired by fish-passage prioritization approaches developed by British Columbia’s Fish Passage Technical Working Group.  


## References {-}

Amiro, P. G. (1993). Habitat measurement and population estimation of juvenile Atlantic salmon (Salmo salar) (Canadian Special Publication of Fisheries and Aquatic Sciences No. 118). Department of Fisheries and Oceans.  
