# Appendix A – Status of Structures Assessed in the Field {-}

## Non-Actionable Barriers
There are currently no barriers that have confirmed habitat upstream but are non-actionable due to other constraints (i.e., low habitat value, short habitat gain, etc in the Bonaparte River, Bessette Creek, and Eagle River watersheds. 

## Data-deficient Barriers {-}
```{r}
#| label: table-16
#| tbl-cap: "Table 16: Structures in Bonaparte River watershed that have been assessed for fish passage for Pacific salmon and steelhead as of May 2026, but either require an additional in-depth fish-passage assessment to confirm the passability status or a habitat assessment to confirm upstream habitat is present."
#| echo: false
#| results: asis
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/tbl-16-bonp-data-deficient.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```

```{r}
#| label: table-17
#| tbl-cap: "Table 17: Structures in Bessette Creek watershed that have been assessed for fish passage for Pacific salmon and steelhead as of May 2026, but either require an additional in-depth fish-passage assessment to confirm the passability status or a habitat assessment to confirm upstream habitat is present."
#| echo: false
#| results: asis
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/tbl-17-bessette-data-deficient.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```

```{r}
#| label: table-18
#| tbl-cap: "Table 18: Structures in Eagle River watershed that have been assessed for fish passage for Pacific salmon and steelhead as of May 2026, but either require an additional in-depth fish-passage assessment to confirm the passability status or a habitat assessment to confirm upstream habitat is present."
#| echo: false
#| results: asis
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/tbl-18-eagle-data-deficient.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```

## Excluded Structures {-}
```{r}
#| label: table-19
#| tbl-cap: "Table 19: Structures in Bonaparte River, Bessette Creek, and Eagle River watersheds that are excluded from further consideration in subsequent ranking and work planning because the structure is not present, is confirmed passable (e.g., bridge), or has no habitat upstream for Pacific salmon and steelhead."
#| echo: false
#| results: asis
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/tbl-19-excluded-structures.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```




